BEGIN;

DROP TRIGGER IF EXISTS trg_payments_create_email_log_on_success ON payments;
DROP TRIGGER IF EXISTS trg_bookings_30_create_notification_on_booking_change ON bookings;
DROP TRIGGER IF EXISTS trg_bookings_20_decrease_inventory_after_confirm ON bookings;
DROP TRIGGER IF EXISTS trg_bookings_10_log_booking_status_change ON bookings;
DROP TRIGGER IF EXISTS trg_bookings_validate_voucher_usage ON bookings;
DROP TRIGGER IF EXISTS trg_refunds_05_validate_status_transition ON refunds;
DROP TRIGGER IF EXISTS trg_payments_05_validate_status_transition ON payments;
DROP TRIGGER IF EXISTS trg_bookings_05_validate_status_transition ON bookings;
DROP TRIGGER IF EXISTS trg_users_prevent_delete_system_admin ON users;
DROP TRIGGER IF EXISTS trg_support_tickets_set_updated_at ON support_tickets;
DROP TRIGGER IF EXISTS trg_promotions_set_updated_at ON promotions;
DROP TRIGGER IF EXISTS trg_payments_set_updated_at ON payments;
DROP TRIGGER IF EXISTS trg_bookings_set_updated_at ON bookings;
DROP TRIGGER IF EXISTS trg_carts_set_updated_at ON carts;
DROP TRIGGER IF EXISTS trg_room_types_set_updated_at ON room_types;
DROP TRIGGER IF EXISTS trg_services_set_updated_at ON services;
DROP TRIGGER IF EXISTS trg_roles_set_updated_at ON roles;
DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users;

DROP FUNCTION IF EXISTS create_email_log_on_payment_success();
DROP FUNCTION IF EXISTS create_notification_on_booking_change();
DROP FUNCTION IF EXISTS decrease_inventory_after_confirm();
DROP FUNCTION IF EXISTS validate_voucher_usage();
DROP FUNCTION IF EXISTS log_booking_status_change();
DROP FUNCTION IF EXISTS validate_refund_status_transition();
DROP FUNCTION IF EXISTS validate_payment_status_transition();
DROP FUNCTION IF EXISTS validate_booking_status_transition();
DROP FUNCTION IF EXISTS prevent_delete_system_admin();
DROP FUNCTION IF EXISTS set_updated_at();
DROP FUNCTION IF EXISTS write_user_log(TEXT, TEXT, UUID, JSONB);
DROP FUNCTION IF EXISTS app_current_user_id();
DROP FUNCTION IF EXISTS app_setting_text(TEXT);

DROP TABLE IF EXISTS email_logs;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS support_replies;
DROP TABLE IF EXISTS support_tickets;
DROP TABLE IF EXISTS refunds;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS booking_status_histories;
DROP TABLE IF EXISTS booking_items;
DROP TABLE IF EXISTS cart_items;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS vouchers;
DROP TABLE IF EXISTS promotions;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS service_images;
DROP TABLE IF EXISTS train_details;
DROP TABLE IF EXISTS flight_details;
DROP TABLE IF EXISTS room_types;
DROP TABLE IF EXISTS hotel_details;
DROP TABLE IF EXISTS tour_details;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS user_logs;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;

DROP TYPE IF EXISTS email_status;
DROP TYPE IF EXISTS notification_status;
DROP TYPE IF EXISTS support_ticket_status;
DROP TYPE IF EXISTS notification_type;
DROP TYPE IF EXISTS sender_type;
DROP TYPE IF EXISTS support_ticket_priority;
DROP TYPE IF EXISTS voucher_status;
DROP TYPE IF EXISTS promotion_status;
DROP TYPE IF EXISTS refund_status;
DROP TYPE IF EXISTS payment_status;
DROP TYPE IF EXISTS payment_method;
DROP TYPE IF EXISTS payment_provider;
DROP TYPE IF EXISTS discount_type;
DROP TYPE IF EXISTS booking_item_status;
DROP TYPE IF EXISTS booking_status;
DROP TYPE IF EXISTS cart_status;
DROP TYPE IF EXISTS seat_class;
DROP TYPE IF EXISTS transport_schedule_status;
DROP TYPE IF EXISTS cabin_class;
DROP TYPE IF EXISTS transport_type;
DROP TYPE IF EXISTS service_status;
DROP TYPE IF EXISTS service_type;
DROP TYPE IF EXISTS user_status;

COMMIT;
