export const vietnamAirportOptions = Object.freeze([
  {
    code: 'HAN',
    city: 'Hà Nội',
    airport_name: 'Sân bay quốc tế Nội Bài',
    province: 'Hà Nội',
    label: 'Hà Nội (HAN)',
  },
  {
    code: 'SGN',
    city: 'TP. Hồ Chí Minh',
    airport_name: 'Sân bay quốc tế Tân Sơn Nhất',
    province: 'TP. Hồ Chí Minh',
    label: 'TP. Hồ Chí Minh (SGN)',
  },
  {
    code: 'DAD',
    city: 'Đà Nẵng',
    airport_name: 'Sân bay quốc tế Đà Nẵng',
    province: 'Đà Nẵng',
    label: 'Đà Nẵng (DAD)',
  },
  {
    code: 'CXR',
    city: 'Nha Trang/Cam Ranh',
    airport_name: 'Sân bay quốc tế Cam Ranh',
    province: 'Khánh Hòa',
    label: 'Nha Trang/Cam Ranh (CXR)',
  },
  {
    code: 'PQC',
    city: 'Phú Quốc',
    airport_name: 'Sân bay quốc tế Phú Quốc',
    province: 'Kiên Giang',
    label: 'Phú Quốc (PQC)',
  },
  {
    code: 'HPH',
    city: 'Hải Phòng',
    airport_name: 'Sân bay quốc tế Cát Bi',
    province: 'Hải Phòng',
    label: 'Hải Phòng (HPH)',
  },
  {
    code: 'VII',
    city: 'Vinh',
    airport_name: 'Sân bay quốc tế Vinh',
    province: 'Nghệ An',
    label: 'Vinh (VII)',
  },
  {
    code: 'HUI',
    city: 'Huế',
    airport_name: 'Sân bay quốc tế Phú Bài',
    province: 'Thừa Thiên Huế',
    label: 'Huế (HUI)',
  },
  {
    code: 'VCA',
    city: 'Cần Thơ',
    airport_name: 'Sân bay quốc tế Cần Thơ',
    province: 'Cần Thơ',
    label: 'Cần Thơ (VCA)',
  },
  {
    code: 'DLI',
    city: 'Đà Lạt',
    airport_name: 'Sân bay Liên Khương',
    province: 'Lâm Đồng',
    label: 'Đà Lạt (DLI)',
  },
  {
    code: 'BMV',
    city: 'Buôn Ma Thuột',
    airport_name: 'Sân bay Buôn Ma Thuột',
    province: 'Đắk Lắk',
    label: 'Buôn Ma Thuột (BMV)',
  },
  {
    code: 'UIH',
    city: 'Quy Nhơn',
    airport_name: 'Sân bay Phù Cát',
    province: 'Bình Định',
    label: 'Quy Nhơn (UIH)',
  },
  {
    code: 'PXU',
    city: 'Pleiku',
    airport_name: 'Sân bay Pleiku',
    province: 'Gia Lai',
    label: 'Pleiku (PXU)',
  },
  {
    code: 'VCL',
    city: 'Chu Lai',
    airport_name: 'Sân bay Chu Lai',
    province: 'Quảng Nam',
    label: 'Chu Lai (VCL)',
  },
  {
    code: 'VDH',
    city: 'Đồng Hới',
    airport_name: 'Sân bay Đồng Hới',
    province: 'Quảng Bình',
    label: 'Đồng Hới (VDH)',
  },
  {
    code: 'TBB',
    city: 'Tuy Hòa',
    airport_name: 'Sân bay Tuy Hòa',
    province: 'Phú Yên',
    label: 'Tuy Hòa (TBB)',
  },
  {
    code: 'THD',
    city: 'Thanh Hóa',
    airport_name: 'Sân bay Thọ Xuân',
    province: 'Thanh Hóa',
    label: 'Thanh Hóa (THD)',
  },
  {
    code: 'DIN',
    city: 'Điện Biên',
    airport_name: 'Sân bay Điện Biên',
    province: 'Điện Biên',
    label: 'Điện Biên (DIN)',
  },
  {
    code: 'VKG',
    city: 'Rạch Giá',
    airport_name: 'Sân bay Rạch Giá',
    province: 'Kiên Giang',
    label: 'Rạch Giá (VKG)',
  },
  {
    code: 'CAH',
    city: 'Cà Mau',
    airport_name: 'Sân bay Cà Mau',
    province: 'Cà Mau',
    label: 'Cà Mau (CAH)',
  },
  {
    code: 'VCS',
    city: 'Côn Đảo',
    airport_name: 'Sân bay Côn Đảo',
    province: 'Bà Rịa - Vũng Tàu',
    label: 'Côn Đảo (VCS)',
  },
  {
    code: 'VDO',
    city: 'Vân Đồn',
    airport_name: 'Sân bay quốc tế Vân Đồn',
    province: 'Quảng Ninh',
    label: 'Vân Đồn (VDO)',
  },
])
